# <p style="text-align:center;">Tensorflow - II</p>
---
*<p style="text-align:right;">Reference: Tensorflow Official Docs</p>*


In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensors

Tensors are multi-dimensional arrays with a uniform type (called a `dtype`). You can see all supported dtypes at `tf.dtypes.DType`.

If you're familiar with NumPy, tensors are (kind of) like `np.arrays`.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

## 1. Basics

First, create some basic tensors.

Here is a "scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".

In [2]:
rank_0_tensor = tf.constant(69)
print(rank_0_tensor)

tf.Tensor(69, shape=(), dtype=int32)


A "vector" or "rank-1" tensor has one axis

In [3]:
rank_1_tensor = tf.constant([2,3,4])
print(rank_1_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


A "matrix" or "rank-2" tensor has two axes

In [4]:
rank_2_tensor = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


You can convert a tensor to a NumPy array either using `np.array` or the `tensor.numpy` method:

In [5]:
np.array(rank_2_tensor)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
rank_2_tensor.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

The base `tf.Tensor` class requires tensors to be "rectangular" -- that is, along each axis, every element is the same size. Howeve, there are specialized types of tensors that can handle different shapes:
* Ragged tensors
* Sparse tensors

Basic maths can be done on tensors as shown

In [8]:
a = tf.constant([[1, 2],[3, 4]])
b = tf.constant([[1, 1],[1, 1]])

print(tf.add(a,b),"\n")
print(tf.multiply(a,b),"\n")
print(tf.matmul(a,b),"\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [9]:
print(a + b, "\n", a*b, "\n", a@b, "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 
 tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



Tensors are used in all kind of operations

In [10]:
c = tf.constant([[4.0,5.0],[10.0,1.0]])

print(tf.reduce_sum(c))

#index of largest value
print(tf.math.argmax(c))

#compute softmax
print(tf.nn.softmax(c))

tf.Tensor(20.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


Note: Typically, anywhere a TensorFlow function expects a Tensor as input, the function will also accept anything that can be converted to a Tensor using `tf.convert_to_tensor`. See below for an example.

In [11]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [12]:
tf.reduce_max([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

You can convery a tensor to a NumPy array either using `np.array` or the `tensor.numpy` method

In [13]:
rank_2_tensor.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.array(rank_2_tensor)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 2. About Shapes

Tensors have shapes. Some vocabulary:

* **Shape**: The length (number of elements) of each of the axes of a tensor.
* **Rank**: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* **Axis** or **Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor, the product of the shape vector's elements.
> **Note**: Although you may see reference to a "tensor of two dimensions", a rank-2 tensor does not usually describe a 2D space.

Tensors and tf.TensorShape objects have convenient properties for accessing these:


In [15]:
rank_4_tensor = tf.zeros([3,2,4,5])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [16]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [17]:
#axis 0            axis -1
#   ^                 ^
#   |                 |
#|--3--|--2--|--4--|--5--|

But note that the `Tensor.ndim` and `Tensor.shape` attributes don't return `Tensor` objects. If you need a Tensor use the `tf.rank` or `tf.shape` function. This difference is subtle, but it can be important when building graphs (later).

In [18]:
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [19]:
tf.shape(rank_4_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5])>

While axes are often referred to by their indices, you should always keep track of the meaning of each. Often axes are ordered from global to local: The batch axis first, followed by spatial dimensions, and features for each location last. This way feature vectors are contiguous regions of memory.

In [20]:
#Batch   Height Width  Features
#   ^     ^     ^      ^
#   |     |     |      |
#|--3--|--2--|--4--|--5--|
#<---------Rank 4-------->

## 3. Indexing

### Single-Axis Indexing
TensorFlow follows standard Python indexing rules, similar to indexing a list or a string in Python, and the basic rules for NumPy indexing.

indexes start at `0`
negative indices count backwards from the end
colons, `:`, are used for slices: `start:stop:step`

In [21]:
rank_1_tensor = tf.constant([0,1,1,2,3,5,8,13,21,34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


Indexing with a scalar removes the axis:

In [22]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


Indexing with a `:` keeps the axis:

In [23]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


### Multi-Axis Indexing

Higher rank tensors are indexed by passing multiple indices. The exact rules as in the single-axis case apply to each axis independently.

In [24]:
print(rank_2_tensor.numpy())

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Passing an integer for each index, the result is a scalar.

In [25]:
print(rank_2_tensor[1,1].numpy())

5


In [26]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [4 5 6]
Second column: [2 5 8]
Last row: [7 8 9]
First item in last column: 3
Skip the first row:
[[4 5 6]
 [7 8 9]] 



Here is an example ousing a 3-axis tensor:

In [27]:
print(rank_3_tensor[:,:,4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


## 4. Manipulating Shapes

Reshaping a tensor is of great utility

In [28]:
x = tf.constant([[1],[2],[3]])
print(x.shape)

(3, 1)


The shape tuple can be converted to a python list using `var.shape.as_list` function

In [29]:
print(x.shape.as_list())

[3, 1]


The tensor can be reshaped using `tf.reshape()` feature. This is fast and cheap since the underlying data does not need to be duplicated

In [30]:
reshaped = tf.reshape(x, [1,3])

In [31]:
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


The data maintains its layout in memory and a new tensor is created, with the requested shape, pointing to the same data. TensorFlow uses C-style "row-major" memory ordering, where incrementing the rightmost index corresponds to a single step in memory.

In [32]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


If you flatten a tensor you can see what order it is laid out in memeory

In [33]:
tf.reshape(rank_3_tensor, [-1])

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])>

Typically the only reasonable use of `tf.reshape` is to combine or split adjacent axes (ir add/remove `1`s).

For this 3x2x2 tensor, reshaping to (3x2)x5 or 3x(2x5) are both reasonable things to do, as the slices do not mix:

In [34]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3,-1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


>***Note that this method can also be used to preserve axes upto a certain axis***

Reshaping will "work" for any new shape with the same total number of elements, but it will not do anything useful if you do not respect the order of the axes.

Swapping axes in `tf.reshape` does not work; you need `tf.transpose` for that.

In [35]:
# Bad examples: don't do this

# You can't reorder axes with reshape.
print(tf.reshape(rank_3_tensor, [2,3,5]), "\n") 

# This is a mess
print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

# This doesn't work at all
try:
  tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


Some bad reshapes
![ing1](https://www.tensorflow.org/static/guide/images/tensor/reshape-bad.png)
![img2](https://www.tensorflow.org/static/guide/images/tensor/reshape-bad4.png)
![img3](https://www.tensorflow.org/static/guide/images/tensor/reshape-bad2.png)

You may run across not-fully-specified shapes. Either the shape contains a None (an axis-length is unknown) or the whole shape is None (the rank of the tensor is unknown).

Except for `tf.RaggedTensor`, such shapes will only occur in the context of TensorFlow's symbolic, graph-building APIs:

* `tf.function`
* The keras functional API.

## 5. More on DTypes
To inspect a `tf.Tensor`'s data type use the `Tensor.dtype` property.

When creating a `tf.Tensor` from a Python object you may optionally specify the datatype.

If you don't, TensorFlow chooses a datatype that can represent your data. TensorFlow converts Python integers to `tf.int32` and Python floating point numbers to `tf.float32`. Otherwise TensorFlow uses the same rules NumPy uses when converting to arrays.

You can cast from type to type.

In [36]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


## 6. Broadcasting

Broadcasting is a concept borrowed from the equivalent feature in NumPy. In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.

### `tf.convert_to_tensor`
Most ops, like `tf.matmul` and `tf.reshape` take arguments of class `tf.Tensor`. However, you'll notice in the above case, Python objects shaped like tensors are accepted.

Most, but not all, ops call `convert_to_tensor` on non-tensor arguments. There is a registry of conversions, and most object classes like NumPy's `ndarray`, `TensorShape`, Python lists, and `tf.Variable` will all convert automatically.

See `tf.register_tensor_conversion_function` for more details, and if you have your own type you'd like to automatically convert to a tensor.

## 7. Ragged Tensors

A tensor with variable numbers of elements along some axis is called "ragged". Use `tf.ragged.RaggedTensor` for ragged data.

For example, This cannot be represented as a regular tensor: A `tf.RaggedTensor`, shape: [4, None]

![img](https://www.tensorflow.org/static/guide/images/tensor/ragged.png)

Instead create a `tf.RaggedTensor` using `tf.ragged.constant`:

In [37]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [38]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


The shape of a `tf.RaggedTensor` will contain some axes with unknown lengths:

In [39]:
print(ragged_tensor.shape)

(4, None)


## 8. String Tensors

`tf.string` is a dtype, which is to say you can represent data as strings (variable-length byte arrays) in tensors.

The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the axes of the tensor. See `tf.strings` for functions to manipulate them.

Here is a scalar string tensor:

In [40]:
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


A vector of strings

In [41]:
tensor_of_strings = tf.constant(["Gray wolf", "Quick Brown Fox", "Lazy Dog"])
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick Brown Fox' b'Lazy Dog'], shape=(3,), dtype=string)


In the above printout the `b` prefix indicates that `tf.string` dtype is not a unicode string, but a `byte-string`. See the Unicode Tutorial for more about working with unicode text in TensorFlow.

If you pass unicode characters they are utf-8 encoded.

In [42]:
tf.constant("🥳👍")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

Basic String Functions

In [43]:
print(tf.strings.split(scalar_string_tensor, sep = " "))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [44]:
text = tf.constant("1 100 256")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1. 100. 256.], shape=(3,), dtype=float32)


## 9. Sparse Tensors

Sometimes, your data is sparse, like a very wide embedding space. TensorFlow supports `tf.sparse.SparseTensor` and related operations to store sparse data efficiently.

In [45]:
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,0],[1,2]], 
                                       values = [1,2], 
                                       dense_shape = [3,4])
print(sparse_tensor,"\n")

#You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
